version: '3.4'

services:
  calendarevents.api:
    image: shaharshokrani/calendarevents_api
    build:
      context: .
      dockerfile: CalendarEvents.API/Dockerfile    
    environment:
      - DatabaseServer=database
      - DatabaseName=CalendarEventsApiDB
      - DatabasePort=1433
      - DatabaseUser=sa
      - DatabasePassword=<YourStrong@Passw0rd>
      - ASPNETCORE_ENVIRONMENT=Development      
    container_name: calendarevents_api_container
    ports:
      - "5001:80"
    networks:
      - back-tier
    depends_on:
      - database

  database:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1443:1433"
    environment:
      - SA_PASSWORD=<YourStrong@Passw0rd>
      - ACCEPT_EULA=Y    
      - MSSQL_PID=Express
    container_name: calendarevents_database_container
    networks:      
      - back-tier

networks:
  back-tier: